// TODO: Update mock data to match the actual data structure after database is implemented
import type { Asset } from '@/types/asset';

export const mockAssets: Asset[] = [
  // --- KPI ---
  {
    id: '1',
    title: 'KPI Dashboard 1',
    name: 'KPI Dashboard Template 1',
    summary: 'Short sentence for mock display',
    category: 'KPI',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/1',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-04-13T10:00:00Z',
    updated_at: '2025-03-02T10:00:00Z',
    featured: true,
    trending: true,
    tags: ['KPI'],
    kpi_data: {},
  },
  {
    id: '2',
    title: 'KPI Dashboard 2',
    name: 'KPI Dashboard Template 2',
    summary: 'Short sentence for mock display',
    category: 'KPI',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/2',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-03-16T10:00:00Z',
    updated_at: '2025-03-31T10:00:00Z',
    tags: ['KPI'],
    kpi_data: {},
  },
  {
    id: '3',
    title: 'KPI Dashboard 3',
    name: 'KPI Dashboard Template 3',
    summary: 'Short sentence for mock display',
    category: 'KPI',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/3',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-03-31T10:00:00Z',
    updated_at: '2025-04-05T10:00:00Z',
    tags: ['KPI'],
    kpi_data: {},
  },
  {
    id: '4',
    title: 'KPI Dashboard 4',
    name: 'KPI Dashboard Template 4',
    summary: 'Short sentence for mock display',
    category: 'KPI',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/4',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-04-14T10:00:00Z',
    updated_at: '2025-04-04T10:00:00Z',
    featured: true,
    tags: ['KPI'],
    kpi_data: {},
  },
  {
    id: '5',
    title: 'KPI Dashboard 5',
    name: 'KPI Dashboard Template 5',
    summary: 'Short sentence for mock display',
    category: 'KPI',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/5',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-02-09T10:00:00Z',
    updated_at: '2025-02-14T10:00:00Z',
    tags: ['KPI'],
    kpi_data: {},
  },
  {
    id: '6',
    title: 'KPI Dashboard 6',
    name: 'KPI Dashboard Template 6',
    summary: 'Short sentence for mock display',
    category: 'KPI',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/6',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-27T10:00:00Z',
    updated_at: '2025-02-11T10:00:00Z',
    tags: ['KPI'],
    kpi_data: {},
  },

  // --- Layout ---
  {
    id: '7',
    title: 'Layout 1',
    name: 'Layout Template 1',
    summary: 'Short sentence for mock display',
    category: 'Layout',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/7',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-02-14T10:00:00Z',
    updated_at: '2025-03-01T10:00:00Z',
    trending: true,
    tags: ['Layout'],
    layout_data: {
      pages: 8,
      type: 'Universal',
      used: 4,
      questions: [
        {
          id: 'q1',
          text: 'Is the layout clear?',
          description: 'Evaluate if the layout structure is easy to understand'
        },
        {
          id: 'q2',
          text: 'Does it follow guidelines?',
          description: 'Check if the layout adheres to design standards'
        }
      ],
    },
  },
  {
    id: '8',
    title: 'Layout 2',
    name: 'Layout Template 2',
    summary: 'Short sentence for mock display',
    category: 'Layout',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/8',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-22T10:00:00Z',
    updated_at: '2025-02-11T10:00:00Z',
    tags: ['Layout'],
    layout_data: {
      pages: 8,
      type: 'Universal',
      used: 4,
      questions: [
        {
          id: 'q1',
          text: 'Is the layout clear?',
          description: 'Evaluate if the layout structure is easy to understand'
        },
        {
          id: 'q2',
          text: 'Does it follow guidelines?',
          description: 'Check if the layout adheres to design standards'
        }
      ],
    },
  },
  {
    id: '9',
    title: 'Layout 3',
    name: 'Layout Template 3',
    summary: 'Short sentence for mock display',
    category: 'Layout',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/9',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-03-15T10:00:00Z',
    updated_at: '2025-03-26T10:00:00Z',
    tags: ['Layout'],
    layout_data: {
      pages: 8,
      type: 'Universal',
      used: 4,
      questions: [
        {
          id: 'q1',
          text: 'Is the layout clear?',
          description: 'Evaluate if the layout structure is easy to understand'
        },
        {
          id: 'q2',
          text: 'Does it follow guidelines?',
          description: 'Check if the layout adheres to design standards'
        }
      ],
    },
  },
  {
    id: '10',
    title: 'Layout 4',
    name: 'Layout Template 4',
    summary: 'Short sentence for mock display',
    category: 'Layout',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/10',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-04-15T10:00:00Z',
    updated_at: '2025-04-12T10:00:00Z',
    featured: true,
    tags: ['Layout'],
    layout_data: {
      pages: 8,
      type: 'Universal',
      used: 4,
      questions: [
        {
          id: 'q1',
          text: 'Is the layout clear?',
          description: 'Evaluate if the layout structure is easy to understand'
        },
        {
          id: 'q2',
          text: 'Does it follow guidelines?',
          description: 'Check if the layout adheres to design standards'
        }
      ],
    },
  },
  {
    id: '11',
    title: 'Layout 5',
    name: 'Layout Template 5',
    summary: 'Short sentence for mock display',
    category: 'Layout',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/11',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-02-27T10:00:00Z',
    updated_at: '2025-03-06T10:00:00Z',
    tags: ['Layout'],
    layout_data: {
      pages: 8,
      type: 'Universal',
      used: 4,
      questions: [
        {
          id: 'q1',
          text: 'Is the layout clear?',
          description: 'Evaluate if the layout structure is easy to understand'
        },
        {
          id: 'q2',
          text: 'Does it follow guidelines?',
          description: 'Check if the layout adheres to design standards'
        }
      ],
    },
  },
  {
    id: '12',
    title: 'Layout 6',
    name: 'Layout Template 6',
    summary: 'Short sentence for mock display',
    category: 'Layout',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/12',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-02-04T10:00:00Z',
    tags: ['Layout'],
    layout_data: {
      pages: 8,
      type: 'Universal',
      used: 4,
      questions: [
        {
          id: 'q1',
          text: 'Is the layout clear?',
          description: 'Evaluate if the layout structure is easy to understand'
        },
        {
          id: 'q2',
          text: 'Does it follow guidelines?',
          description: 'Check if the layout adheres to design standards'
        }
      ],
    },
  },

  // --- Storyboards ---
  {
    id: '13',
    title: 'Storyboard 1',
    name: 'Storyboard Template 1',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/13',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-04-16T10:00:00Z',
    updated_at: '2025-03-06T10:00:00Z',
    featured: true,
    trending: true,
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '14',
    title: 'Storyboard 2',
    name: 'Storyboard Template 2',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/14',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-19T10:00:00Z',
    updated_at: '2025-02-08T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '15',
    title: 'Storyboard 3',
    name: 'Storyboard Template 3',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/15',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-03-03T10:00:00Z',
    updated_at: '2025-03-13T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '16',
    title: 'Storyboard 4',
    name: 'Storyboard Template 4',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/16',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-20T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '17',
    title: 'Storyboard 5',
    name: 'Storyboard Template 5',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/17',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-03-06T10:00:00Z',
    updated_at: '2025-03-20T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '18',
    title: 'Storyboard 6',
    name: 'Storyboard Template 6',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/18',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-11T10:00:00Z',
    updated_at: '2025-01-28T10:00:00Z',
    featured: true,
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '19',
    title: 'Storyboard 7',
    name: 'Storyboard Template 7',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/19',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-15T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '20',
    title: 'Storyboard 8',
    name: 'Storyboard Template 8',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/20',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-03-10T10:00:00Z',
    updated_at: '2025-03-25T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '21',
    title: 'Storyboard 9',
    name: 'Storyboard Template 9',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/21',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-02-17T10:00:00Z',
    updated_at: '2025-03-01T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '22',
    title: 'Storyboard 10',
    name: 'Storyboard Template 10',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/22',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-18T10:00:00Z',
    updated_at: '2025-02-06T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '23',
    title: 'Storyboard 11',
    name: 'Storyboard Template 11',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/23',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-03-01T10:00:00Z',
    updated_at: '2025-03-18T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
  {
    id: '24',
    title: 'Storyboard 12',
    name: 'Storyboard Template 12',
    summary: 'Short sentence for mock display',
    category: 'Storyboards',
    description: 'This is a slightly longer mock description used for previewing asset detail layout and testing overflow cases.',
    url: 'https://example.com/assets/24',
    thumbnail_url: 'https://placehold.co/300x300?text=Asset',
    created_at: '2025-01-12T10:00:00Z',
    updated_at: '2025-01-29T10:00:00Z',
    tags: ['Storyboards'],
    storyboard_data: {},
  },
];
